language: node_js

stages:
  - test
  - name: publish module
    if:
      - branch = master
      - tag IS present
      - repo = ocadotechnology/hexagonjs
  - name: publish docs
    if:
      - branch = add_pages
      - repo = ocadotechnology/hexagonjs
      - type = push

node_js:
  - "9"
  - "8"
  - "7"
  - "6"

jobs:
  include:
    - stage: test
      script: npm test && npm run combine-coverage && npm run upload-coverage

    - stage: publish module
      script: skip
      node_js: "6"
      deploy:
        provider: npm
        email: hexagonj.ci.noreply@ocado.com
        api_key:
          secure: $GITHUB_TOKEN

    - stage: publish pages
      script: cd docs && npm install && npm run clean && npm run build
      node_js: "8"
      deploy:
        provider: pages
        local-dir: docs/public
        email: hexagonj.ci.noreply@ocado.com
        github-token: $GITHUB_TOKEN
        skip-cleanup: true
        keep-history: true
