language: node_js

node_js:
  - "9"
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"

jobs:
  include:
    - stage: test
      script: npm test && npm run combine-coverage && npm run upload-coverage

    - stage: publish module
      script: skip
      node_js: "4"
      deploy:
        provider: npm
        email: hexagonj.ci.noreply@ocado.com
        api_key:
          secure: $GITHUB_TOKEN
        on:
          branch: master
          repo: ocadotechnology/hexagonjs
          tags: true

    - stage: publish pages
      script: cd docs && npm install && npm run clean && npm run build
      node_js: "4"
      deploy:
        provider: pages
        local-dir: docs/public
        email: hexagonj.ci.noreply@ocado.com
        github-token: $GITHUB_TOKEN
        skip-cleanup: true
        keep-history: true
        on:
          branch: add_pages
          repo: ocadotechnology/hexagonjs
          tags: true
