language: node_js

node_js:
  - '9'
  - '8'
  - '7'
  - '6'

env:
  global:
    secure: Nv9uLt1TOIDhbLfFwKs5QnxFHN9xHKporOwdY9bC+7qqjfqoZ7LOpkrajE+qRkc/cU9iper2RIuyMzGN8W0uLYyZak/1ZeHT5FfGI5exj0iX5gH/psE+KfbHp3X4D19zIvUDFFowZ0oMiCax9bRsuk8tzAToPL4Unv3X9WhMN4EICLs0wHqRNyaoD3VdbQV6dfUhQvpQDxKgXQ05cO4Ugf8S7OPFIh5Wwu8lnsV1UobOxk1/SDyXvAYqtn3TPZGxaY2MujIz8C8xkzz0BMaKV5Jd8ZOhQW4Q9b8USQB24smnmi+Kuf0vUqxtnRtbYxLwLMUC/5/lWGnBu+tfmwR2vgaRZ8wtAH9k/tT+vguJLsgJ2Ro/TnBpQ1fMw5uF8YZcASzJzmeIF12jaXNS3bXnFr4qEkQtPwF+D/njYiRMKrqHFbNr0mSToqvosomhpOjrJ5AAKocPzj/eiwfdhlvNCXfLxRVnj7SdwPxsUc/EBTf1FfN066oKeUb8yq/qzFggd4W7MVHUBPTHS8aaDYy33RZdxrevAjlVMxij7QmsACzP6b/V/G3T4AvWStaZJa3Z/ILSsH+gLuv7TrjTrhvKkfGpYMD+5pzo8v9Ffq3BYUPt+4Z4gNpXbx2+cVTwpjgAyQJQS048CnDiVB5aSMgmUlgDnVmp5D/ZJSjMGgejDdo=

stages:
  - test

  - name: publish module
    if: tag IS present AND repo = ocadotechnology/hexagonjs

  - name: publish pages
    if: branch = 1-17-0 AND repo = ocadotechnology/hexagonjs AND NOT type = pull_request

jobs:
  include:
  - stage: test
    script: npm test && npm run combine-coverage && npm run upload-coverage

  - stage: publish module
    script: skip
    node_js: '6'
    deploy:
      provider: npm
      email: hexagonjs.ci.noreply@ocado.com
      on:
        tags: true
      api_key:
        secure: uT6EaWejGMY5l74LVmcS7i2jTA/sfPZfaay5319n+3cZUlnNR8sh/ipM1rBQXCnbzuV82HoYKp/IWpzbIW2qlWcMMKmBxL1zFiHF+9va+W4rdxnztGYu5ikX8Dyhyawuw+CwHkpElmp7HZr1r014s0MuNoFjXlQDqfugGFbHJrgB6Wu4skn/pwjfZRe8tBko4TzjKSkG8CTwdp1mMKtM7eWVQ2C0bB4r1pQuOLWW1en7I2B/HztEpH/3roT3duE+5fo+QMTt6wnagzPz1eRKshlt51eJtzpdcbcoHslKuRTC+IYiJHligN8di3SX25ZLQeAddI/FmNgzD6RQFavy9jbAcRYLt1K3xCBb13rDL2ekpXQ54ATrAYiTmwfD7R7rUiGwGHT0JaACs5vL/vDIJq4dUuwCbMt0TvfnizmlOtiGiSd1JDQqLOlfCeZKeukEP2D4mHAuDQYpSvZCLVfeceevvPmRbEHMXpnjRzW4ZROrMVfEDvKk7OXUfHxJskW10ohE6xUSIsFKqcOLCv9+YK4yD3Wp+II8FYdJfX3xyGDTdVihGAc+CjnO8Ioc7X9nupDrZPZRU4MyD2CR9xU920Zm5oOLRDFsOdDTZ8HpE+15+ASjoVSCiKimeo6YxWYTLXMHPp4yvjnLVlMRB+dNe5R8DrKTjLeQMZBDDWBkSDU=

  - stage: publish pages
    env:
      - GITHUB_PAGES=true
    script: cd docs && npm install && npm run clean && npm run build
    node_js: '8'
    deploy:
      provider: pages
      local-dir: docs/target
      skip-cleanup: true
      keep-history: true
      fqdn: hexagonjs.io
      email: hexagonjs.ci.noreply@ocado.com
      github-token: $GITHUB_TOKEN
