language: node_js

node_js:
  # - '9'
  # - '8'
  # - '7'
  - '6'

env:
  global:
    secure: Nv9uLt1TOIDhbLfFwKs5QnxFHN9xHKporOwdY9bC+7qqjfqoZ7LOpkrajE+qRkc/cU9iper2RIuyMzGN8W0uLYyZak/1ZeHT5FfGI5exj0iX5gH/psE+KfbHp3X4D19zIvUDFFowZ0oMiCax9bRsuk8tzAToPL4Unv3X9WhMN4EICLs0wHqRNyaoD3VdbQV6dfUhQvpQDxKgXQ05cO4Ugf8S7OPFIh5Wwu8lnsV1UobOxk1/SDyXvAYqtn3TPZGxaY2MujIz8C8xkzz0BMaKV5Jd8ZOhQW4Q9b8USQB24smnmi+Kuf0vUqxtnRtbYxLwLMUC/5/lWGnBu+tfmwR2vgaRZ8wtAH9k/tT+vguJLsgJ2Ro/TnBpQ1fMw5uF8YZcASzJzmeIF12jaXNS3bXnFr4qEkQtPwF+D/njYiRMKrqHFbNr0mSToqvosomhpOjrJ5AAKocPzj/eiwfdhlvNCXfLxRVnj7SdwPxsUc/EBTf1FfN066oKeUb8yq/qzFggd4W7MVHUBPTHS8aaDYy33RZdxrevAjlVMxij7QmsACzP6b/V/G3T4AvWStaZJa3Z/ILSsH+gLuv7TrjTrhvKkfGpYMD+5pzo8v9Ffq3BYUPt+4Z4gNpXbx2+cVTwpjgAyQJQS048CnDiVB5aSMgmUlgDnVmp5D/ZJSjMGgejDdo=

stages:
  - test

  - name: publish module
    if: tag IS present AND branch = master AND repo = ocadotechnology/hexagonjs

  - name: publish docs
    if: branch = master AND repo = ocadotechnology/hexagonjs

jobs:
  include:
  - stage: test
    script: npm test && npm run upload-coverage

  - stage: publish module
    script: skip
    node_js: '6'
    deploy:
      provider: npm
      email: hexagonjs.ci.noreply@ocado.com
      api_key:
        secure: GpXKIC946J3acPqCmUCMUa+/g6vHh0mSkAw0ut7HpLYUBpUnNKZGHNePevOum/jxeAjMQOSAIlUW9nWo2A9wkrx7hV7mwIhTOhIQiSqGrQ/kOyAEWNXWGgrKSlzbEyOzUVJfSfesfPgGSc2gO6JjgCFuxgi7nEMrjyUdCf5Vl7lYq6HqQtbO3wcguDtq9lYbxwZ4PoDf8bN2j2aanj/Fk9KcyqAdIrUdRmOq5U3k0BcaQg31w1iaOPr4ES3UoxN/QCa+m+5ZqBYdt2Ekms7Hb8rukneTV94XaaRT2qmdQAAZfi7X66yO/z14nlpEO3z+i5kYeutdw7KoTVNhKCmbrscTB+pJ6agGk7pZkrEAlRH3DIo9k3VPo/GeifflpUWZXvQwzfEq3iaO6XtgN63NITMcuhXqykjk+u2DSCUhyiNuwf/WYlbAJWp+vYo+fnHQGpt/jRAedVPFad+NDfbJxUXluEnMCE1ujpflyIXdab3yZFrO5Hg36xdwd2tq3vAXRm/3R39h38EMLn1DkD9O5OWY0AkbXfzLLtYydmD8JHOXD9R8yzeaudcQi3Gkqt5K1dVqmNDsjP6eaC5aMRmUqRFTqt06wmQxS8yFSQQZCJDTIPztYmfb54icFNRAklA4I2QRKd/WGQ4PtBxnLQOa8zeuAp4T61aHxNx21Znt5Ts=

  - stage: publish pages
    script: cd docs && npm install && npm run clean && npm run build
    node_js: '8'
    deploy:
      provider: pages
      local-dir: docs/public
      skip-cleanup: true
      keep-history: true
      email: hexagonjs.ci.noreply@ocado.com
      github-token: $GITHUB_TOKEN
